Created a MyEvents page.
CMPUT301F24napkin/napkinfactory pull request #16
Opened 2024-11-02 01:26 UTC by antoszko

Added some functionality for button presses as well as made it more modular so we can reuse the EventsList code a little better. IMO I think its better to reuse the code but if theres a good reason we should have 2 seperate XMLs and ArrayAdapters for the general EventsList (user) and MyEvents List (organizer) then please let me know!

2024-11-02 01:30 UTC, antoszko commented
So the ugly part is the constructor for EventListArrayAdapter 'feels' wrong to ask for button callback, button text, and button icon but I'm not sure how else to architect it.

2024-11-02 01:46 UTC, Sherali5543 requested changes
A couple small changes. Also added thoughts on constructor

2024-11-02 01:46 UTC, Sherali5543 commented on napkinapp/app/src/main/java/com/example/napkinapp/MainActivity.java
> +                        .replace(R.id.content_fragmentcontainer, new MyEventsFragment())
undo this change

2024-11-02 01:46 UTC, Sherali5543 commented on napkinapp/app/src/main/java/com/example/napkinapp/MainActivity.java
> +import com.example.napkinapp.fragments.myevents.MyEventsFragment;
remove the import as well

2024-11-02 01:46 UTC, Sherali5543 commented on napkinapp/app/src/main/java/com/example/napkinapp/MainActivity.java
>                  // Myevents
Also add it to here to allow for navigation

2024-11-02 01:46 UTC, Sherali5543 commented on napkinapp/app/src/main/java/com/example/napkinapp/fragments/listevents/ListEventsFragment.java
> +
remove breaking change

2024-11-02 01:46 UTC, Sherali5543 commented on napkinapp/app/src/main/java/com/example/napkinapp/fragments/listevents/EventArrayAdapter.java
> +        this.onClickListener = onClickListener;
maybe instead of passing the on click listener we can have an interface that is implemented by the specific fragment? I don't hate this solution tho

2024-11-02 01:46 UTC, Sherali5543 commented on napkinapp/app/src/main/java/com/example/napkinapp/fragments/listevents/EventArrayAdapter.java
> +        this.onClickListener = onClickListener;
similarily can have a setup button function to set text and drawable attached to the interface

2024-11-02 01:47 UTC, Sherali5543 commented on napkinapp/app/src/main/java/com/example/napkinapp/fragments/listevents/ListEventsFragment.java
> +
there was an equal sign that I guess you removed while I was reviewing lmao

2024-11-03 05:11 UTC, Sherali5543 requested changes
I'm not sure if I merge this if there'll be issues considering you have changes abs has already made. But other than the constrain layout change it lgtm

2024-11-03 05:11 UTC, Sherali5543 commented on napkinapp/app/build.gradle.kts
> +    implementation(platform(libs.firebase.bom.v3271))
this as well

2024-11-03 05:11 UTC, Sherali5543 commented on napkinapp/app/src/main/java/com/example/napkinapp/utils/DB_Client.java
> +package com.example.napkinapp.utils;
once again this should've been added in abs' pr. Idk if you just didn't rebase

2024-11-03 05:11 UTC, Sherali5543 commented on napkinapp/build.gradle.kts
> +    id("com.google.gms.google-services") version "4.4.2" apply false
same thing

2024-11-03 05:11 UTC, Sherali5543 commented on napkinapp/gradle/libs.versions.toml
> +firebaseAnalytics = "22.1.2"
should've been added by abs

2024-11-03 05:11 UTC, Sherali5543 commented on napkinapp/app/src/main/res/layout/event_list_footer_button.xml
> +    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
I think using a constraint layout is a better approach. allows for it be centered easier

2024-11-07 23:38 UTC, Deenknight approved these changes
lgtm!!!!!!!!!!!!!1!11!!1!11!!!

2024-11-07 23:53 UTC, merged