Admin user and event search
CMPUT301F24napkin/napkinfactory pull request #84
Opened 2024-12-01 03:05 UTC by Wumbo12347

fixed showing all events when the page loads for both admin user and event search.

added cascading deletes for users and events

2024-12-01 03:15 UTC, Sherali5543 commented
please add some tests

2024-12-01 03:50 UTC, antoszko commented on napkinapp/app/src/main/java/com/example/napkinapp/fragments/admineventsearch/AdminListEventsFragment.java
>      private void
formatting?

2024-12-01 04:27 UTC, antoszko commented
It doesn't actually do a deep delete for delete user nor delete event.
For delete event, you need to loop through all the waitlist, chosen, and registered lists, go into each user stored there, and remove that eventId from the user's respective list.

For delete user, you  need to loop through all their waitlist, chosen, and registered lists, go into each event in that list, and remove that userId from the event's respective list,
Additionally for delete user, you need loop through each of the user's events and call the deleteEvent function. ^

2024-12-02 00:59 UTC, antoszko requested changes

2024-12-02 00:59 UTC, antoszko commented on napkinapp/app/src/main/java/com/example/napkinapp/fragments/adminusersearch/AdminListUsersFragment.java
> +            Log.i("Button", String.format("List Events: Clicked on event %s\n", user.getName()));
comment should say user not event

2024-12-02 00:59 UTC, antoszko commented on napkinapp/app/src/main/java/com/example/napkinapp/fragments/adminusersearch/AdminListUsersFragment.java
> +        // remove events which the deleted user has created
isn't this already handled in deleteUserFromCancelledListsANDORGANIZEDEVENTS??

2024-12-02 00:59 UTC, antoszko commented on napkinapp/app/src/main/java/com/example/napkinapp/fragments/adminusersearch/AdminListUsersFragment.java
> +        // remove events which the deleted user has created
Also this is shallow delete so would need to fix that anyways. but I beleive you already do this in tha aforementioned function

2024-12-02 00:59 UTC, antoszko commented on napkinapp/app/src/main/java/com/example/napkinapp/fragments/adminusersearch/AdminListUsersFragment.java
> +                Toast.makeText(mContext, "Failed to delete event: " + e.getMessage(), Toast.LENGTH_SHORT).show();
toast message

2024-12-02 00:59 UTC, antoszko commented on napkinapp/app/src/main/java/com/example/napkinapp/fragments/adminusersearch/AdminListUsersFragment.java
> +            Toast.makeText(mContext, "Delete User", Toast.LENGTH_SHORT).show();
remove this toast, deleteUser() already does toasts

2024-12-02 10:50 UTC, antoszko approved these changes

2024-12-02 10:50 UTC, merged